# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_credit_amount', models.IntegerField()),
                ('water_credit_amount', models.IntegerField()),
            ],
        ),
    ]
